package com.qyub.mgr2.ui.theme

import androidx.compose.ui.graphics.Color

val PrimaryLight = Color(0xFF4A6CF7)
val OnPrimaryLight = Color(0xFFFFFFFF)
val SecondaryLight = Color(0xFFF7B32B)
val OnSecondaryLight = Color(0xFF000000)
val BackgroundLight = Color(0xFFFFFFFF)
val OnBackgroundLight = Color(0xFF1A1A1A)
val SurfaceLight = Color(0xFFF5F5F5)
val OnSurfaceLight = Color(0xFF1A1A1A)
val OutlineLight = Color(0xFFBDBDBD)
val OnSurfaceVariantLight = Color(0xFF5A5A5A)
val DisabledTextLight = Color(0xFF9E9E9E)

val PrimaryDark = Color(0xFF4A6CF7)
val OnPrimaryDark = Color(0xFFFFFFFF)
val SecondaryDark = Color(0xFFF7B32B)
val OnSecondaryDark = Color(0xFF000000)
val BackgroundDark = Color(0xFF121212)
val OnBackgroundDark = Color(0xFFEAEAEA)
val SurfaceDark = Color(0xFF1E1E1E)
val OnSurfaceDark = Color(0xFFEAEAEA)
val OutlineDark = Color(0xFFA3A3A3)
val OnSurfaceVariantDark = Color(0xFFAAAAAA)
val DisabledTextDark = Color(0xFF666666)

val EventColorCrimson = Color(0xffe81436)
val EventColorOrange = Color(0xffe86014)
val EventColorSun = Color(0xffe8ac14)
val EventColorLime = Color(0xfface814)
val EventColorEmerald = Color(0xff60e814)
val EventColorMint = Color(0xff14e860)
val EventColorTurquoise = Color(0xff14e8ac)
val EventColorSky = Color(0xff1436e8)
val EventColorIndigo = Color(0xff6014e8)
val EventColorLavender = Color(0xffac14e8)
val EventColorMagenta = Color(0xffe814ac)
val EventColorFlamingo = Color(0xffe81460)
